eureka:
  client:
    service-url:
       defaultZone: http://localhost:9060/eureka

management.endpoints.web.exposure.include: '*'

management:
  endpoint:
    health:
      show-details: ALWAYS
      
management.endpoints.web.path-mapping.cereebro: /cereebro/snitch